version: '{build}'
skip_tags: true
image: Visual Studio 2017
configuration: Release
test: off
build_script:
- ps: ./Build.ps1
artifacts:
- path: artifacts/Masking.Serilog.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: lTJxDDmCcpdJzotq6hPPgIisms65MVK9Kmq6/plkLfNJsLrUz40cF2EdYSCOgdda
  skip_symbols: true
  on:
    branch: /^(master|develop)$/
    
