version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  verbosity: minimal
artifacts:
- path: '**/Masking.Serilog.*.nupkg'
  name: package
deploy:
- provider: NuGet
  api_key:
    secure: lTJxDDmCcpdJzotq6hPPgIisms65MVK9Kmq6/plkLfNJsLrUz40cF2EdYSCOgdda
  skip_symbols: true
  artifact: package